DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(12,2) NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL,
    checked BOOLEAN DEFAULT false NOT NULL,
    category grocery NOT NULL
);


--DEMO CODE BELOW--

-- CREATE TABLE IF NOT EXISTS whopipe_video_views (
--     view_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     video_name TEXT NOT NULL,
--     region TEXT NOT NULL,
--     date_viewed TIMESTAMP DEFAULT now() NOT NULL
-- );

-- DROP TYPE IF EXISTS department;
-- CREATE TYPE department AS ENUM (
--     'Electronics',
--     'Cleaning',
--     'Grocery',
--     'Furniture',
--     'Stationery',
--     'Clothing',
--     'DIY',
--     'Sports',
--     'Homeware',
--     'Games',
--     'Transport'
-- );

-- CREATE TABLE IF NOT EXISTS amazong_products (
--     product_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     name TEXT NOT NULL,
--     price decimal(12,2) NOT NULL,
--     image TEXT,
--     category department NOT NULL
-- );